services:
  db:
    image: mongo:latest
    container_name: db
    command: ['--replSet', 'rs0', '--bind_ip_all']
    ports:
      - '27017:27017'
    volumes:
      - db_data:/data/db
    networks:
      - app-network
  # Next.js application
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs_app
    ports:
      - '3000:3000'
    environment:
      # Next.js sẽ dùng biến này (cấu hình ở next.config.js hoặc process.env)
      MONGODB_URI: mongodb://db:27017/mydb?replicaSet=rs0
    depends_on:
      - db
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
