import type { Metadata } from "next";
import "@/app/globals.css"
import { inter } from '@/accets/fonts/fonts';
import NavBar from "@/components/headers/navbar";
import { AuthProvider } from "@/context/AuthContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// REVIEW: Prettier isn't working
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}
      ><AuthProvider>
          <div className="md:px-30"><NavBar /></div>

          {children}</AuthProvider>
      </body>
    </html>
  );
}
